name: innoviahub
region: nyc

services:
  - name: backend
    git:
      repo_clone_url: https://github.com/khaled99xp/InnoviaHub.git
      branch: main
    dockerfile_path: backend/Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: "/api"
    envs:
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
        scope: RUN_AND_BUILD_TIME
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
        scope: RUN_TIME
      - key: DB_HOST
        value: ${DB_HOST}
        scope: RUN_TIME
      - key: DB_PORT
        value: ${DB_PORT}
        scope: RUN_TIME
      - key: DB_NAME
        value: ${DB_NAME}
        scope: RUN_TIME
      - key: DB_USER
        value: ${DB_USER}
        scope: RUN_TIME
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
        scope: RUN_TIME
        type: SECRET
      - key: DB_CONNECTION_STRING
        value: "Server=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_PASSWORD};SslMode=Required;"
        scope: RUN_TIME
      - key: ConnectionStrings__DefaultConnection
        value: ${DB_CONNECTION_STRING}
        scope: RUN_TIME
      - key: Jwt__Issuer
        value: ${JWT_ISSUER}
        scope: RUN_TIME
      - key: Jwt__Audience
        value: ${JWT_AUDIENCE}
        scope: RUN_TIME
      - key: Jwt__SecretKey
        value: ${JWT_SECRET}
        scope: RUN_TIME
        type: SECRET
      - key: OpenAI__ApiKey
        value: ${OPENAI_API_KEY}
        scope: RUN_TIME
        type: SECRET
      - key: Cors__AllowedOrigins
        value: ${FRONTEND_ORIGIN}
        scope: RUN_TIME

  - name: frontend
    git:
      repo_clone_url: https://github.com/khaled99xp/InnoviaHub.git
      branch: main
    dockerfile_path: frontend/Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: "/"
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME


