name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]
    paths:
      - '.do/app.yaml'
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/deploy-digitalocean.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Validate app spec
        run: |
          echo "=== App Spec Content ==="
          cat .do/app.yaml
          echo "=== Checking for cluster_name ==="
          if grep -q "cluster_name" .do/app.yaml; then
            echo "ERROR: cluster_name found in app.yaml!"
            grep -n "cluster_name" .do/app.yaml
            exit 1
          else
            echo "✓ No cluster_name found - OK"
          fi

      - name: Create or update app
        run: |
          APP_ID=$(doctl apps list --format ID,Spec.Name --no-header | awk '$2=="innoviahub" {print $1}')
          if [ -z "$APP_ID" ]; then
            echo "Creating new app..."
            doctl apps create --spec .do/app.yaml --wait
          else
            echo "Updating app $APP_ID..."
            doctl apps update $APP_ID --spec .do/app.yaml --wait
          fi


