name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - "InnoviaHub_Grupp5.sln"
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for Azure federated credentials
      contents: read # Required for actions/checkout
    env:
      DOTNET_ENVIRONMENT: CI

    steps:
      # 1. Get the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0"

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore InnoviaHub_Grupp5.sln

      # 4. Build the backend (skip OpenAPI generation in CI)
      - name: Build
        run: dotnet build InnoviaHub_Grupp5.sln --configuration Release --no-restore /p:OpenApiGenerateDocuments=false

      # 5. Run tests (optional, can be skipped if tests fail)
      - name: Test
        run: dotnet test backend.Tests/backend.Tests.csproj --configuration Release --no-build --verbosity normal
        continue-on-error: true

      # 6. Publish project (creates a package for deployment)
      - name: Publish
        run: dotnet publish backend/backend.csproj -c Release -o ./publish --no-build /p:OpenApiGenerateDocuments=false

      # 7. List published files (for debugging)
      - name: List published files
        run: |
          echo "Published files:"
          ls -la ./publish/
          echo "---"
          echo "wwwroot files:"
          ls -la ./publish/wwwroot/ 2>/dev/null || echo "No wwwroot directory"

      # 8. Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_02EE843DE02E4178BC50AA77A306E28A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_29E680B20C714CBA989E142D2F9D8DBB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C79FB9F745FD4475B75EBD4C3FEC25D1 }}

      # 9. Deploy to Azure Web App
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "InnoviaHub"
          package: ./publish
